"""Turning what the agent computed into what a person can check.

The model produces a sentence. This module produces the two things shown underneath
it: the table the sentence was derived from, and a chart of that table. Neither is
generated by the model, and that is the point — the evidence has to be independent of
the narration, or it is not evidence.

WHY THE CHART IS BUILT HERE AND NOT BY `create_chart`
-----------------------------------------------------
`create_chart` charts *stored columns*: it resolves `x` and `y` against the dataset's
schema and aggregates them in SQL. That is exactly right for "sales by region", and it
cannot express the most common real question at all:

    "which country generated the most revenue?"

There is no `revenue` column. Revenue is `Quantity * UnitPrice`, the agent computes it
in `execute_sql`, and the result exists only as rows in a tool payload. Asking
`create_chart` for it fails with "no such column: revenue", and a model that has just
computed the answer correctly then burns two turns arguing with a tool.

So charts come from the *result table* rather than from the dataset. The output is the
same spec shape `create_chart` emits, so the renderer does not know or care which
produced it. When the agent did call `create_chart`, that spec wins: it was a
deliberate choice about presentation, and this fallback is not.

WHY THE LAST RESULT AND NOT THE FIRST
--------------------------------------
An agent's early calls are orientation — a schema read, a distinct-value check, a
failed guess at a column name. The call that produced the answer is the last one that
returned rows. Picking the first would show a person the agent's throat-clearing and
label it evidence.
"""

from __future__ import annotations

from typing import Any

from app.agent.charts import choose_chart
from app.tools.base import ToolResult

# One bar is not a comparison. The upper bound now lives in `app/agent/charts.py`,
# which decides the TYPE from the shape: many rows become a line rather than a wall
# of unreadable bars.
_MIN_CHART_POINTS = 2
_HISTOGRAM_BUCKETS = 20

# Tools whose payload is a table of results rather than a description of the dataset.
# `inspect_schema` is excluded deliberately: it always succeeds and always returns
# rows, so including it would make the schema listing the "evidence" for every answer
# where the real query happened to come earlier.
_TABULAR_TOOLS = frozenset({"execute_sql", "compare_groups"})


def table_from_results(results: list[ToolResult]) -> dict[str, Any] | None:
    """The evidence table: the last successful tabular result that returned rows."""
    for result in reversed(results):
        if not result.ok or result.tool not in _TABULAR_TOOLS:
            continue
        table = _as_table(result)
        if table and table["rows"]:
            return table
    return None


def _as_table(result: ToolResult) -> dict[str, Any] | None:
    """Normalise a tool payload into `{columns, rows}`.

    Two tools, two shapes: `execute_sql` already returns columns and rows, while
    `compare_groups` returns a list of dicts whose keys vary with the aggregation
    (`share_of_total` is present for sums and absent for averages, on purpose). Keys
    are read from the first entry rather than hardcoded, so a change in that tool does
    not silently drop a column here.
    """
    data = result.data

    if result.tool == "execute_sql":
        columns = list(data.get("columns") or [])
        rows = [list(row) for row in (data.get("rows") or [])]
        return {"columns": columns, "rows": rows} if columns else None

    if result.tool == "compare_groups":
        groups: list[dict[str, Any]] = data.get("groups") or []
        if not groups:
            return None
        headers = list(groups[0])
        # The generic key names are unhelpful next to a sentence about countries and
        # revenue, and the tool tells us what they actually were.
        labels = {
            "group": str(data.get("group_column") or "group"),
            "value": f"{data.get('aggregation', 'value')}({data.get('metric_column', '')})",
        }
        return {
            "columns": [labels.get(h, h) for h in headers],
            "rows": [[group.get(h) for h in headers] for group in groups],
        }

    return None


def chart_from_results(
    results: list[ToolResult], table: dict[str, Any] | None, question: str
) -> dict[str, Any] | None:
    """A chart spec: the agent's own if it made one, otherwise derived from the table."""
    for result in reversed(results):
        if result.ok and result.tool == "create_chart" and result.data.get("chart"):
            return result.data
    return _chart_from_table(table, question)


def _chart_from_table(table: dict[str, Any] | None, question: str) -> dict[str, Any] | None:
    """A chart of the result, of whatever type the result's shape calls for.

    Returning None is a real outcome and not a failure. A single-row answer ("the
    correlation is -0.001") has nothing to compare; a chart drawn anyway would be
    decoration presented as analysis — and a one-cell table under a sentence already
    containing that number is the same mistake in a different shape.
    """
    if not table or not table["rows"]:
        return None

    columns: list[str] = table["columns"]
    rows: list[list[Any]] = table["rows"]

    kind = choose_chart(columns, rows, question)
    if kind is None:
        return None
    if kind == "histogram":
        return _histogram(columns, rows, question)
    if kind == "scatter":
        return _scatter(columns, rows, question)
    return _categorical(kind, columns, rows, question)


def _categorical(
    kind: str, columns: list[str], rows: list[list[Any]], question: str
) -> dict[str, Any] | None:
    """bar, line or pie: one label column against one numeric column."""
    label_index = _first_label_column(columns, rows)
    value_index = _first_numeric_column(rows, skip=label_index)
    if label_index is None or value_index is None:
        return None

    points = [
        {"x": _as_label(row[label_index]), "y": float(row[value_index])}
        for row in rows
        if _is_number(row[value_index])
    ]
    if len(points) < _MIN_CHART_POINTS:
        return None

    return _spec(
        kind,
        question,
        x={"column": columns[label_index], "kind": "categorical", "label": columns[label_index]},
        y={"column": columns[value_index], "kind": "numeric", "label": columns[value_index]},
        points=points,
    )


def _scatter(columns: list[str], rows: list[list[Any]], question: str) -> dict[str, Any] | None:
    """Two numeric columns against each other."""
    numeric = [i for i in range(len(columns)) if any(_is_number(row[i]) for row in rows)]
    if len(numeric) < 2:
        return None
    x_index, y_index = numeric[0], numeric[1]
    points = [
        {"x": float(row[x_index]), "y": float(row[y_index])}
        for row in rows
        if _is_number(row[x_index]) and _is_number(row[y_index])
    ]
    if len(points) < _MIN_CHART_POINTS:
        return None
    return _spec(
        "scatter",
        question,
        x={"column": columns[x_index], "kind": "numeric", "label": columns[x_index]},
        y={"column": columns[y_index], "kind": "numeric", "label": columns[y_index]},
        points=points,
    )


def _histogram(columns: list[str], rows: list[list[Any]], question: str) -> dict[str, Any] | None:
    """One numeric column, bucketed.

    Bucketed here rather than in SQL because the rows are already in hand: asking the
    database again would be a round trip to recompute something we are holding.
    """
    index = next((i for i in range(len(columns)) if any(_is_number(r[i]) for r in rows)), None)
    if index is None:
        return None
    values = sorted(float(row[index]) for row in rows if _is_number(row[index]))
    if len(values) < _MIN_CHART_POINTS:
        return None

    low, high = values[0], values[-1]
    if low == high:
        return None

    bucket_count = min(_HISTOGRAM_BUCKETS, max(5, len(values) // 4))
    width = (high - low) / bucket_count
    counts = [0] * bucket_count
    for value in values:
        # The maximum lands exactly on the top edge and would index one past the end.
        slot = min(int((value - low) / width), bucket_count - 1)
        counts[slot] += 1

    points = [
        {"x": _bucket_label(low + i * width, low + (i + 1) * width), "y": count}
        for i, count in enumerate(counts)
    ]
    return _spec(
        "histogram",
        question,
        x={"column": columns[index], "kind": "numeric", "label": columns[index]},
        y={"column": "count", "kind": "numeric", "label": "rows"},
        points=points,
    )


def _spec(
    kind: str,
    question: str,
    *,
    x: dict[str, Any],
    y: dict[str, Any],
    points: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "chart": {
            "type": kind,
            "title": _title(y["label"], x["label"], question),
            "x": x,
            "y": y,
            "data": points,
            "point_count": len(points),
            # Says where this came from, so a spec derived from a result table is never
            # mistaken for one the agent deliberately specified.
            "derived_from": "the final query result",
        }
    }


def _bucket_label(low: float, high: float) -> str:
    digits = 0 if abs(high - low) >= 10 else 2
    return f"{low:,.{digits}f}-{high:,.{digits}f}"


def _first_label_column(columns: list[str], rows: list[list[Any]]) -> int | None:
    """The first column that reads as a category rather than a measurement."""
    for index in range(len(columns)):
        if all(not _is_number(row[index]) for row in rows if row[index] is not None):
            return index
    # Every column is numeric — a year or a month number is still a fine x-axis.
    return 0 if len(columns) >= 2 else None


def _first_numeric_column(rows: list[list[Any]], *, skip: int | None) -> int | None:
    """The first numeric column that is not the label."""
    width = len(rows[0])
    for index in range(width):
        if index == skip:
            continue
        if any(_is_number(row[index]) for row in rows):
            return index
    return None


def _is_number(value: Any) -> bool:
    # bool is an int in Python, and a column of True/False is a flag, not a magnitude.
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _as_label(value: Any) -> str:
    return "(null)" if value is None else str(value)


def _title(value_column: str, label_column: str, question: str) -> str:
    """Prefer the question as the title; fall back to describing the axes.

    The question is what the person actually wants the chart labelled with, and it is
    already known to be short because the API caps it. Anything long or empty falls back
    to a mechanical description rather than being truncated mid-word.
    """
    cleaned = " ".join(question.split())
    if 0 < len(cleaned) <= 80:
        return cleaned
    return f"{value_column} by {label_column}"
