"""conversations, answer cache and thread position

Revision ID: 158b25f58c9b
Revises: 4c302b0b5876
Create Date: 2026-08-29 00:08:53.787326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '158b25f58c9b'
down_revision: Union[str, Sequence[str], None] = '4c302b0b5876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version', sa.Integer(), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'dataset_version', 'question_hash', 'llm_model', name='uq_answer_cache_key')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analyses', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.add_column('analyses', sa.Column('turn_index', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'analyses', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_column('analyses', 'turn_index')
    op.drop_column('analyses', 'conversation_id')
    op.drop_table('conversations')
    op.drop_table('answer_cache')
    # ### end Alembic commands ###
