"""analyses remember which model answered

Revision ID: 4c302b0b5876
Revises: 53e9a58525be
Create Date: 2026-08-28 21:25:33.339391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c302b0b5876'
down_revision: Union[str, Sequence[str], None] = '53e9a58525be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('llm_model', sa.String(length=128), nullable=True))
    op.add_column('analyses', sa.Column('llm_thinking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'llm_thinking')
    op.drop_column('analyses', 'llm_model')
    # ### end Alembic commands ###
