"""analyses job queue and event log

Revision ID: 53e9a58525be
Revises: 2262de9ce03e
Create Date: 2026-08-28 11:01:18.711678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53e9a58525be'
down_revision: Union[str, Sequence[str], None] = '2262de9ce03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name='ck_analyses_status'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_analyses_dataset_id', 'analyses', ['dataset_id'], unique=False)
    op.create_index('ix_analyses_pending', 'analyses', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('ix_analyses_running_heartbeat', 'analyses', ['heartbeat_at'], unique=False, postgresql_where=sa.text("status = 'RUNNING'"))
    op.create_table('analysis_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_events_analysis_id', 'analysis_events', ['analysis_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_events_analysis_id', table_name='analysis_events')
    op.drop_table('analysis_events')
    op.drop_index('ix_analyses_running_heartbeat', table_name='analyses', postgresql_where=sa.text("status = 'RUNNING'"))
    op.drop_index('ix_analyses_pending', table_name='analyses', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_analyses_dataset_id', table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
